// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lrofbumospouflcegtbc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxyb2ZidW1vc3BvdWZsY2VndGJjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxNTMyMzMsImV4cCI6MjA3MjcyOTIzM30.Vfq3xDIzwX8KY4UrkPv9t4or11NXovXHSDLPzhaNi8k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});